/**
 * ========================================
 * Badge Seeder (Exactly 20 Badges with Cloudinary URLs)
 * ========================================
 */

require('dotenv').config();
const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');
const Badge = require('../models/Badge');
const { BADGE_TYPES } = require('../constants');

// Load Cloudinary URLs from JSON mapping (generated by uploadImagesToCloudinary.js)
let uploadedBadges = {};
try {
  const jsonPath = path.join(__dirname, 'uploaded_badges.json');
  if (fs.existsSync(jsonPath)) {
    uploadedBadges = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
    console.log('✅ Loaded Cloudinary URLs from uploaded_badges.json');
  } else {
    console.warn('⚠️ Warning: uploaded_badges.json not found, using local paths.');
  }
} catch (err) {
  console.warn('⚠️ Warning: Could not load uploaded_badges.json, using local paths.', err.message);
}

// Helper to get Cloudinary URL if available, fallback to local path
const getIconUrl = (filename, localFallback) => {
  return uploadedBadges[filename] || localFallback;
};

const badges = [
  // 1. Bước đầu tiên
  {
    name: 'Bước đầu tiên',
    description: 'Hoàn thành 5 bài học đầu tiên!',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'lessons_complete', value: 5, description: 'Hoàn thành 5 bài học' },
    xpReward: 50,
    starsReward: 20,
    order: 1,
    iconUrl: getIconUrl('Bước đầu tiên.png', 'image/Ảnh nhiệm vụ/Bước đầu tiên.png'),
  },
  // 2. Nhà ngôn ngữ nhí
  {
    name: 'Nhà ngôn ngữ nhí',
    description: 'Học tập tích lũy đạt 500 điểm XP!',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'xp_total', value: 500, description: 'Tích lũy được 500 điểm XP' },
    xpReward: 100,
    starsReward: 40,
    order: 2,
    iconUrl: getIconUrl('Nhà ngôn ngữ nhí.png', 'image/Ảnh nhiệm vụ/Nhà ngôn ngữ nhí.png'),
  },
  // 3. Bậc thầy phụ âm
  {
    name: 'Bậc thầy phụ âm',
    description: 'Luyện viết phụ âm 200 lần.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'writing_practice', value: 200, description: 'Luyện viết phụ âm 200 lần' },
    xpReward: 150,
    starsReward: 60,
    order: 3,
    iconUrl: getIconUrl('Bậc thầy phụ âm.png', 'image/Ảnh nhiệm vụ/Bậc thầy phụ âm.png'),
  },
  // 4. Khám phá nguyên âm
  {
    name: 'Khám phá nguyên âm',
    description: 'Hoàn thành 24 bài học nguyên âm.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'reading_lessons_complete', value: 24, description: 'Hoàn thành 24 bài nguyên âm' },
    xpReward: 150,
    starsReward: 80,
    order: 4,
    iconUrl: getIconUrl('Khám phá nguyên âm.png', 'image/Ảnh nhiệm vụ/Khám phá nguyên âm.png'),
  },
  // 5. Vua nguyên âm
  {
    name: 'Vua nguyên âm',
    description: 'Đọc đúng 500 từ vựng Khmer.',
    type: BADGE_TYPES.LEVEL,
    requirement: { type: 'reading_correct', value: 500, description: 'Đọc đúng 500 từ' },
    xpReward: 400,
    starsReward: 200,
    order: 5,
    iconUrl: getIconUrl('Vua nguyên âm.png', 'image/Ảnh nhiệm vụ/Vua nguyên âm.png'),
  },
  // 6. Chính tả giỏi
  {
    name: 'Chính tả giỏi',
    description: 'Luyện viết từ vựng 400 lần.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'writing_practice', value: 400, description: 'Luyện viết từ vựng 400 lần' },
    xpReward: 300,
    starsReward: 150,
    order: 6,
    iconUrl: getIconUrl('Chính tả giỏi.png', 'image/Ảnh nhiệm vụ/Chính tả giỏi.png'),
  },
  // 7. Phát âm chuẩn
  {
    name: 'Phát âm chuẩn',
    description: 'Luyện phát âm thành công 250 lần.',
    type: BADGE_TYPES.PRONUNCIATION,
    requirement: { type: 'speaking_success', value: 250, description: 'Phát âm thành công 250 lần' },
    xpReward: 250,
    starsReward: 120,
    order: 7,
    iconUrl: getIconUrl('Phát âm chuẩn.png', 'image/Ảnh nhiệm vụ/Phát âm chuẩn.png'),
  },
  // 8. Tai thính
  {
    name: 'Tai thính',
    description: 'Hoàn thành 250 bài luyện nghe.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'listening_complete', value: 250, description: 'Hoàn thành 250 bài nghe' },
    xpReward: 250,
    starsReward: 120,
    order: 8,
    iconUrl: getIconUrl('Tai thính.png', 'image/Ảnh nhiệm vụ/Tai thính.png'),
  },
  // 9. Viết chữ đẹp
  {
    name: 'Viết chữ đẹp',
    description: 'Luyện viết hoàn hảo 500 lần.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'writing_practice', value: 500, description: 'Luyện viết 500 lần' },
    xpReward: 600,
    starsReward: 350,
    order: 9,
    iconUrl: getIconUrl('Viết chữ đẹp.png', 'image/Ảnh nhiệm vụ/Viết chữ đẹp.png'),
  },
  // 10. Ngôi sao đầu tiên
  {
    name: 'Ngôi sao đầu tiên',
    description: 'Tích lũy được 300 ngôi sao.',
    type: BADGE_TYPES.RANKING,
    requirement: { type: 'stars_total', value: 300, description: 'Sở hữu 300 ngôi sao' },
    xpReward: 150,
    starsReward: 80,
    order: 10,
    iconUrl: getIconUrl('Ngôi sao đầu tiên.png', 'image/Ảnh nhiệm vụ/Ngôi sao đầu tiên.png'),
  },
  // 11. Sao sáng
  {
    name: 'Sao sáng',
    description: 'Tích lũy được 1.500 ngôi sao.',
    type: BADGE_TYPES.RANKING,
    requirement: { type: 'stars_total', value: 1500, description: 'Sở hữu 1500 ngôi sao' },
    xpReward: 500,
    starsReward: 250,
    order: 11,
    iconUrl: getIconUrl('Sao sáng.png', 'image/Ảnh nhiệm vụ/Sao sáng.png'),
  },
  // 12. Siêu sao
  {
    name: 'Siêu sao',
    description: 'Sở hữu 5.000 ngôi sao lấp lánh bầu trời.',
    type: BADGE_TYPES.RANKING,
    requirement: { type: 'stars_total', value: 5000, description: 'Sở hữu 5000 ngôi sao' },
    xpReward: 1000,
    starsReward: 600,
    order: 12,
    iconUrl: getIconUrl('Siêu sao.png', 'image/Ảnh nhiệm vụ/Siêu sao.png'),
  },
  // 13. Chăm chỉ
  {
    name: 'Chăm chỉ',
    description: 'Đạt chuỗi học tập liên tục 7 ngày.',
    type: BADGE_TYPES.STREAK,
    requirement: { type: 'streak_days', value: 7, description: 'Chuỗi học tập liên tục 7 ngày' },
    xpReward: 100,
    starsReward: 50,
    order: 13,
    iconUrl: getIconUrl('Chăm chỉ.png', 'image/Ảnh nhiệm vụ/Chăm chỉ.png'),
  },
  // 14. Kiên trì
  {
    name: 'Kiên trì',
    description: 'Duy trì chuỗi học tập liên tục 50 ngày.',
    type: BADGE_TYPES.STREAK,
    requirement: { type: 'streak_days', value: 50, description: 'Chuỗi học tập liên tục 50 ngày' },
    xpReward: 500,
    starsReward: 250,
    order: 14,
    iconUrl: getIconUrl('Kiên trì.png', 'image/Ảnh nhiệm vụ/Kiên trì.png'),
  },
  // 15. Game thủ nhí
  {
    name: 'Game thủ nhí',
    description: 'Hoàn thành 40 trò chơi học tập.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'games_played', value: 40, description: 'Hoàn thành 40 trò chơi' },
    xpReward: 150,
    starsReward: 60,
    order: 15,
    iconUrl: getIconUrl('Game thủ nhí.png', 'image/Ảnh nhiệm vụ/Game thủ nhí.png'),
  },
  // 16. Vô địch mini game
  {
    name: 'Vô địch mini game',
    description: 'Hoàn thành 200 trò chơi bổ ích.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'games_played', value: 200, description: 'Hoàn thành 200 trò chơi' },
    xpReward: 500,
    starsReward: 250,
    order: 16,
    iconUrl: getIconUrl('Vô địch mini game.png', 'image/Ảnh nhiệm vụ/Vô địch mini game.png'),
  },
  // 17. Tốc độ ánh sáng
  {
    name: 'Tốc độ ánh sáng',
    description: 'Duy trì chuỗi học tập liên tục 100 ngày.',
    type: BADGE_TYPES.STREAK,
    requirement: { type: 'streak_days', value: 100, description: 'Chuỗi học tập liên tục 100 ngày' },
    xpReward: 1500,
    starsReward: 800,
    order: 17,
    iconUrl: getIconUrl('Tốc độ ánh sáng.png', 'image/Ảnh nhiệm vụ/Tốc độ ánh sáng.png'),
  },
  // 18. Hoàn hảo
  {
    name: 'Hoàn hảo',
    description: 'Hoàn thành xuất sắc 200 bài học.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'lessons_complete', value: 200, description: 'Hoàn thành 200 bài học' },
    xpReward: 600,
    starsReward: 300,
    order: 18,
    iconUrl: getIconUrl('Hoàn hảo.png', 'image/Ảnh nhiệm vụ/Hoàn hảo.png'),
  },
  // 19. Nhà vô địch
  {
    name: 'Nhà vô địch',
    description: 'Hoàn thành xuất sắc 500 bài học.',
    type: BADGE_TYPES.LEVEL,
    requirement: { type: 'lessons_complete', value: 500, description: 'Hoàn thành 500 bài học' },
    xpReward: 1000,
    starsReward: 1000,
    order: 19,
    iconUrl: getIconUrl('Nhà vô địch.png', 'image/Ảnh nhiệm vụ/Nhà vô địch.png'),
  },
  // 20. Bậc thầy Khmer
  {
    name: 'Bậc thầy Khmer',
    description: 'Hoàn thành tất cả nội dung học — Bậc thầy Khmer!',
    type: BADGE_TYPES.LEVEL,
    requirement: { type: 'content_complete', value: 100, description: 'Hoàn thành 100% nội dung' },
    xpReward: 2000,
    starsReward: 2000,
    order: 20,
    iconUrl: getIconUrl('Bậc thầy Khmer.png', 'image/Ảnh nhiệm vụ/Bậc thầy Khmer.png'),
  }
];

const seedBadges = async () => {
  try {
    console.log('⏳ Seeding exactly 20 Badges with Cloudinary URLs into Database...');
    
    // Clear existing badges
    const deleteResult = await Badge.deleteMany({});
    console.log(`🧹 Cleared ${deleteResult.deletedCount} old badges.`);

    // Insert new badges
    const insertedBadges = await Badge.insertMany(badges);
    console.log(`🎉 Successfully seeded ${insertedBadges.length} new badges with Cloudinary URLs!`);
    
    return insertedBadges;
  } catch (error) {
    console.error('❌ Error seeding badges:', error.message);
    throw error;
  }
};

// If run directly
if (require.main === module) {
  mongoose.connect(process.env.MONGO_URI)
    .then(() => {
      console.log('🔌 Connected to MongoDB for seeding badges.');
      return seedBadges();
    })
    .then(() => {
      console.log('🔌 Closing connection...');
      return mongoose.connection.close();
    })
    .then(() => {
      console.log('👋 Seeder finished successfully.');
      process.exit(0);
    })
    .catch((err) => {
      console.error('❌ Fatal error in seeder:', err);
      process.exit(1);
    });
}

module.exports = seedBadges;
