/**
 * ========================================
 * Badge Seeder (Exactly 20 Badges with Cloudinary URLs)
 * ========================================
 */

require('dotenv').config();
const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');
const Badge = require('../models/Badge');
const { BADGE_TYPES } = require('../constants');

// Load Cloudinary URLs from JSON mapping (generated by uploadImagesToCloudinary.js)
let uploadedBadges = {};
try {
  const jsonPath = path.join(__dirname, 'uploaded_badges.json');
  if (fs.existsSync(jsonPath)) {
    uploadedBadges = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
    console.log('✅ Loaded Cloudinary URLs from uploaded_badges.json');
  } else {
    console.warn('⚠️ Warning: uploaded_badges.json not found, using local paths.');
  }
} catch (err) {
  console.warn('⚠️ Warning: Could not load uploaded_badges.json, using local paths.', err.message);
}

// Helper to get Cloudinary URL if available, fallback to local path
const getIconUrl = (filename, localFallback) => {
  return uploadedBadges[filename] || localFallback;
};

const badges = [
  // 1. Bước đầu tiên
  {
    name: 'Bước đầu tiên',
    description: 'Hoàn thành bài học đầu tiên của bé!',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'lessons_complete', value: 1, description: 'Hoàn thành bài học đầu tiên' },
    xpReward: 30,
    starsReward: 3,
    order: 1,
    iconUrl: getIconUrl('Bước đầu tiên.png', 'image/Ảnh nhiệm vụ/Bước đầu tiên.png'),
  },
  // 2. Nhà ngôn ngữ nhí
  {
    name: 'Nhà ngôn ngữ nhí',
    description: 'Học tập tích lũy đạt 50 điểm XP!',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'xp_total', value: 50, description: 'Tích lũy được 50 điểm XP' },
    xpReward: 30,
    starsReward: 3,
    order: 2,
    iconUrl: getIconUrl('Nhà ngôn ngữ nhí.png', 'image/Ảnh nhiệm vụ/Nhà ngôn ngữ nhí.png'),
  },
  // 3. Bậc thầy phụ âm
  {
    name: 'Bậc thầy phụ âm',
    description: 'Đạt trình độ viết phụ âm cấp độ 1.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'writing_level', value: 1, description: 'Đạt trình độ viết phụ âm cấp độ 1' },
    xpReward: 40,
    starsReward: 4,
    order: 3,
    iconUrl: getIconUrl('Bậc thầy phụ âm.png', 'image/Ảnh nhiệm vụ/Bậc thầy phụ âm.png'),
  },
  // 4. Khám phá nguyên âm
  {
    name: 'Khám phá nguyên âm',
    description: 'Đạt trình độ đọc nguyên âm cấp độ 1.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'reading_level', value: 1, description: 'Đạt trình độ đọc nguyên âm cấp độ 1' },
    xpReward: 40,
    starsReward: 4,
    order: 4,
    iconUrl: getIconUrl('Khám phá nguyên âm.png', 'image/Ảnh nhiệm vụ/Khám phá nguyên âm.png'),
  },
  // 5. Vua nguyên âm
  {
    name: 'Vua nguyên âm',
    description: 'Xuất sắc đạt trình độ đọc nguyên âm cấp độ 2.',
    type: BADGE_TYPES.LEVEL,
    requirement: { type: 'reading_level', value: 2, description: 'Đọc nguyên âm đạt cấp độ 2' },
    xpReward: 50,
    starsReward: 5,
    order: 5,
    iconUrl: getIconUrl('Vua nguyên âm.png', 'image/Ảnh nhiệm vụ/Vua nguyên âm.png'),
  },
  // 6. Chính tả giỏi
  {
    name: 'Chính tả giỏi',
    description: 'Đạt trình độ viết phụ âm cấp độ 2.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'writing_level', value: 2, description: 'Viết phụ âm đạt cấp độ 2' },
    xpReward: 50,
    starsReward: 5,
    order: 6,
    iconUrl: getIconUrl('Chính tả giỏi.png', 'image/Ảnh nhiệm vụ/Chính tả giỏi.png'),
  },
  // 7. Phát âm chuẩn
  {
    name: 'Phát âm chuẩn',
    description: 'Đạt trình độ nói phát âm cấp độ 1.',
    type: BADGE_TYPES.PRONUNCIATION,
    requirement: { type: 'speaking_level', value: 1, description: 'Cấp độ Nói đạt từ 1 trở lên' },
    xpReward: 50,
    starsReward: 5,
    order: 7,
    iconUrl: getIconUrl('Phát âm chuẩn.png', 'image/Ảnh nhiệm vụ/Phát âm chuẩn.png'),
  },
  // 8. Tai thính
  {
    name: 'Tai thính',
    description: 'Đạt trình độ nghe tiếng Khmer cấp độ 1.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'listening_level', value: 1, description: 'Cấp độ Nghe đạt từ 1 trở lên' },
    xpReward: 40,
    starsReward: 4,
    order: 8,
    iconUrl: getIconUrl('Tai thính.png', 'image/Ảnh nhiệm vụ/Tai thính.png'),
  },
  // 9. Viết chữ đẹp
  {
    name: 'Viết chữ đẹp',
    description: 'Đạt trình độ viết Khmer cấp độ 3.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'writing_level', value: 3, description: 'Viết chữ đạt cấp độ 3' },
    xpReward: 100,
    starsReward: 10,
    order: 9,
    iconUrl: getIconUrl('Viết chữ đẹp.png', 'image/Ảnh nhiệm vụ/Viết chữ đẹp.png'),
  },
  // 10. Ngôi sao đầu tiên
  {
    name: 'Ngôi sao đầu tiên',
    description: 'Tích lũy được 15 ngôi sao danh giá đầu tiên.',
    type: BADGE_TYPES.RANKING,
    requirement: { type: 'stars_total', value: 15, description: 'Sở hữu 15 ngôi sao' },
    xpReward: 50,
    starsReward: 5,
    order: 10,
    iconUrl: getIconUrl('Ngôi sao đầu tiên.png', 'image/Ảnh nhiệm vụ/Ngôi sao đầu tiên.png'),
  },
  // 11. Sao sáng
  {
    name: 'Sao sáng',
    description: 'Tích lũy được tổng cộng 50 ngôi sao lấp lánh.',
    type: BADGE_TYPES.RANKING,
    requirement: { type: 'stars_total', value: 50, description: 'Sở hữu 50 ngôi sao' },
    xpReward: 80,
    starsReward: 8,
    order: 11,
    iconUrl: getIconUrl('Sao sáng.png', 'image/Ảnh nhiệm vụ/Sao sáng.png'),
  },
  // 12. Siêu sao
  {
    name: 'Siêu sao',
    description: 'Sở hữu 150 ngôi sao rực rỡ lấp lánh bầu trời.',
    type: BADGE_TYPES.RANKING,
    requirement: { type: 'stars_total', value: 150, description: 'Sở hữu 150 ngôi sao' },
    xpReward: 150,
    starsReward: 15,
    order: 12,
    iconUrl: getIconUrl('Siêu sao.png', 'image/Ảnh nhiệm vụ/Siêu sao.png'),
  },
  // 13. Chăm chỉ
  {
    name: 'Chăm chỉ',
    description: 'Đạt chuỗi học tập liên tục 2 ngày.',
    type: BADGE_TYPES.STREAK,
    requirement: { type: 'streak_days', value: 2, description: 'Chuỗi học tập liên tục 2 ngày' },
    xpReward: 30,
    starsReward: 3,
    order: 13,
    iconUrl: getIconUrl('Chăm chỉ.png', 'image/Ảnh nhiệm vụ/Chăm chỉ.png'),
  },
  // 14. Kiên trì
  {
    name: 'Kiên trì',
    description: 'Duy trì chuỗi học tập bền bỉ liên tục 7 ngày.',
    type: BADGE_TYPES.STREAK,
    requirement: { type: 'streak_days', value: 7, description: 'Chuỗi học tập liên tục 7 ngày' },
    xpReward: 80,
    starsReward: 8,
    order: 14,
    iconUrl: getIconUrl('Kiên trì.png', 'image/Ảnh nhiệm vụ/Kiên trì.png'),
  },
  // 15. Game thủ nhí
  {
    name: 'Game thủ nhí',
    description: 'Chơi hoàn thành 5 trò chơi học tập bổ ích.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'games_played', value: 5, description: 'Hoàn thành 5 trò chơi' },
    xpReward: 30,
    starsReward: 3,
    order: 15,
    iconUrl: getIconUrl('Game thủ nhí.png', 'image/Ảnh nhiệm vụ/Game thủ nhí.png'),
  },
  // 16. Vô địch mini game
  {
    name: 'Vô địch mini game',
    description: 'Xuất sắc hoàn thành 20 trò chơi bổ ích.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'games_played', value: 20, description: 'Hoàn thành 20 trò chơi' },
    xpReward: 120,
    starsReward: 12,
    order: 16,
    iconUrl: getIconUrl('Vô địch mini game.png', 'image/Ảnh nhiệm vụ/Vô địch mini game.png'),
  },
  // 17. Tốc độ ánh sáng
  {
    name: 'Tốc độ ánh sáng',
    description: 'Duy trì chuỗi học tập liên tục 15 ngày.',
    type: BADGE_TYPES.STREAK,
    requirement: { type: 'streak_days', value: 15, description: 'Chuỗi học tập liên tục 15 ngày' },
    xpReward: 200,
    starsReward: 20,
    order: 17,
    iconUrl: getIconUrl('Tốc độ ánh sáng.png', 'image/Ảnh nhiệm vụ/Tốc độ ánh sáng.png'),
  },
  // 18. Hoàn hảo
  {
    name: 'Hoàn hảo',
    description: 'Hoàn thành xuất sắc 15 bài học.',
    type: BADGE_TYPES.LEARNING,
    requirement: { type: 'lessons_complete', value: 15, description: 'Hoàn thành 15 bài học' },
    xpReward: 100,
    starsReward: 10,
    order: 18,
    iconUrl: getIconUrl('Hoàn hảo.png', 'image/Ảnh nhiệm vụ/Hoàn hảo.png'),
  },
  // 19. Nhà vô địch
  {
    name: 'Nhà vô địch',
    description: 'Hoàn thành xuất sắc 30 bài học.',
    type: BADGE_TYPES.LEVEL,
    requirement: { type: 'lessons_complete', value: 30, description: 'Hoàn thành 30 bài học' },
    xpReward: 250,
    starsReward: 25,
    order: 19,
    iconUrl: getIconUrl('Nhà vô địch.png', 'image/Ảnh nhiệm vụ/Nhà vô địch.png'),
  },
  // 20. Bậc thầy Khmer
  {
    name: 'Bậc thầy Khmer',
    description: 'Đạt cấp độ 20, vươn tới danh hiệu Bậc thầy Khmer!',
    type: BADGE_TYPES.LEVEL,
    requirement: { type: 'level_reach', value: 20, description: 'Đạt cấp độ 20' },
    xpReward: 300,
    starsReward: 30,
    order: 20,
    iconUrl: getIconUrl('Bậc thầy Khmer.png', 'image/Ảnh nhiệm vụ/Bậc thầy Khmer.png'),
  }
];

const seedBadges = async () => {
  try {
    console.log('⏳ Seeding exactly 20 Badges with Cloudinary URLs into Database...');
    
    // Clear existing badges
    const deleteResult = await Badge.deleteMany({});
    console.log(`🧹 Cleared ${deleteResult.deletedCount} old badges.`);

    // Insert new badges
    const insertedBadges = await Badge.insertMany(badges);
    console.log(`🎉 Successfully seeded ${insertedBadges.length} new badges with Cloudinary URLs!`);
    
    return insertedBadges;
  } catch (error) {
    console.error('❌ Error seeding badges:', error.message);
    throw error;
  }
};

// If run directly
if (require.main === module) {
  mongoose.connect(process.env.MONGO_URI)
    .then(() => {
      console.log('🔌 Connected to MongoDB for seeding badges.');
      return seedBadges();
    })
    .then(() => {
      console.log('🔌 Closing connection...');
      return mongoose.connection.close();
    })
    .then(() => {
      console.log('👋 Seeder finished successfully.');
      process.exit(0);
    })
    .catch((err) => {
      console.error('❌ Fatal error in seeder:', err);
      process.exit(1);
    });
}

module.exports = seedBadges;
