/**
 * ========================================
 * Mission Seeder
 * ========================================
 */

const fs = require('fs');
const path = require('path');
require('dotenv').config();
const mongoose = require('mongoose');
const Mission = require('../models/Mission');
const { MISSION_TYPES, MISSION_ACTIONS } = require('../constants');

// Load Cloudinary URLs from JSON mapping (generated by uploadImagesToCloudinary.js)
let uploadedBadges = {};
try {
  const jsonPath = path.join(__dirname, 'uploaded_badges.json');
  if (fs.existsSync(jsonPath)) {
    uploadedBadges = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
    console.log('✅ Loaded Cloudinary URLs from uploaded_badges.json');
  } else {
    console.warn('⚠️ Warning: uploaded_badges.json not found, using local paths.');
  }
} catch (err) {
  console.warn('⚠️ Warning: Could not load uploaded_badges.json, using local paths.', err.message);
}

// Helper to get Cloudinary URL if available, fallback to local path
const getIconUrl = (filename, localFallback) => {
  return uploadedBadges[filename] || localFallback;
};

const missions = [
  // --- DAILY MISSIONS ---
  {
    title: 'Nhà thông thái nhí 📚',
    description: 'Hoàn thành bài học mới bất kỳ',
    type: MISSION_TYPES.DAILY,
    action: MISSION_ACTIONS.COMPLETE_LESSON,
    requirement: 2,
    reward: { xp: 60, stars: 20 },
    iconUrl: getIconUrl('Nhà thông thái nhí.png', 'https://res.cloudinary.com/demo/image/upload/v1625070000/missions/complete.png'),
    order: 1,
  },
  {
    title: 'Luyện viết chữ đẹp ✍️',
    description: 'Luyện viết chữ cái qua nhận diện viết tay',
    type: MISSION_TYPES.DAILY,
    action: MISSION_ACTIONS.WRITE_LESSON,
    requirement: 5,
    reward: { xp: 70, stars: 25 },
    iconUrl: getIconUrl('Luyện viết chữ đẹp.png', 'https://res.cloudinary.com/demo/image/upload/v1625070000/missions/write.png'),
    order: 2,
  },
  {
    title: 'Đôi tai nhạy bén 🎧',
    description: 'Luyện nghe phát âm và chọn đúng đáp án',
    type: MISSION_TYPES.DAILY,
    action: MISSION_ACTIONS.LISTEN_LESSON,
    requirement: 5,
    reward: { xp: 60, stars: 20 },
    iconUrl: getIconUrl('Đôi tai nhạy bén.png', 'https://res.cloudinary.com/demo/image/upload/v1625070000/missions/listen.png'),
    order: 3,
  },
  {
    title: 'Giọng ca oanh vàng 🗣️',
    description: 'Phát âm to, rõ ràng và đúng từ vựng',
    type: MISSION_TYPES.DAILY,
    action: MISSION_ACTIONS.SPEAK_LESSON,
    requirement: 3,
    reward: { xp: 80, stars: 25 },
    iconUrl: getIconUrl('Giọng ca oanh vàng.png', 'https://res.cloudinary.com/demo/image/upload/v1625070000/missions/speak.png'),
    order: 4,
  },
  {
    title: 'Vừa học vừa chơi 🎮',
    description: 'Hoàn thành trò chơi ôn tập từ vựng',
    type: MISSION_TYPES.DAILY,
    action: MISSION_ACTIONS.PLAY_GAME,
    requirement: 2,
    reward: { xp: 60, stars: 20 },
    iconUrl: getIconUrl('Vừa học vừa chơi.png', 'https://res.cloudinary.com/demo/image/upload/v1625070000/missions/game.png'),
    order: 5,
  },
  {
    title: 'Điểm số hoàn hảo 🎯',
    description: 'Đạt điểm 100% trong bài học hoặc game',
    type: MISSION_TYPES.DAILY,
    action: MISSION_ACTIONS.COMPLETE_LESSON,
    requirement: 1,
    reward: { xp: 100, stars: 40 },
    iconUrl: getIconUrl('Điểm số hoàn hảo.png', 'https://res.cloudinary.com/demo/image/upload/v1625070000/missions/complete.png'),
    order: 6,
  },
  {
    title: 'Khởi đầu ngày mới ☀️',
    description: 'Hoàn thành 1 bài học trước 12h trưa',
    type: MISSION_TYPES.DAILY,
    action: MISSION_ACTIONS.COMPLETE_LESSON,
    requirement: 1,
    reward: { xp: 50, stars: 15 },
    iconUrl: getIconUrl('Khởi đầu ngày mới.png', 'https://res.cloudinary.com/demo/image/upload/v1625070000/missions/complete.png'),
    order: 7,
  },
  {
    title: 'Thợ săn sao vàng ⭐',
    description: 'Đăng nhập trong ngày',
    type: MISSION_TYPES.DAILY,
    action: MISSION_ACTIONS.DAILY_LOGIN,
    requirement: 1,
    reward: { xp: 50, stars: 15 },
    iconUrl: getIconUrl('Sao sáng.png', 'https://res.cloudinary.com/demo/image/upload/v1625070000/missions/login.png'),
    order: 8,
  },
  {
    title: 'Trí nhớ siêu đỉnh 🔄',
    description: 'Ôn tập lại từ vựng cũ đã học',
    type: MISSION_TYPES.DAILY,
    action: MISSION_ACTIONS.READ_LESSON,
    requirement: 3,
    reward: { xp: 60, stars: 20 },
    iconUrl: getIconUrl('Quyển sách tri thức hoàng gia.png', 'https://res.cloudinary.com/demo/image/upload/v1625070000/missions/read.png'),
    order: 9,
  },
  {
    title: 'Gặp gỡ bạn bè 🏆',
    description: 'Truy cập Bảng xếp hạng',
    type: MISSION_TYPES.DAILY,
    action: MISSION_ACTIONS.DAILY_LOGIN,
    requirement: 1,
    reward: { xp: 50, stars: 15 },
    iconUrl: getIconUrl('Nhà vô địch.png', 'https://res.cloudinary.com/demo/image/upload/v1625070000/missions/login.png'),
    order: 10,
  },

  // --- WEEKLY MISSIONS ---
  {
    title: 'Chuỗi ngày vàng 🔥',
    description: 'Học liên tiếp mỗi ngày',
    type: MISSION_TYPES.WEEKLY,
    action: MISSION_ACTIONS.DAILY_LOGIN,
    requirement: 5,
    reward: { xp: 500, stars: 120 },
    iconUrl: getIconUrl('Chuỗi ngày vàng.png', 'https://res.cloudinary.com/demo/image/upload/v1625070000/missions/weekly_complete.png'),
    order: 11,
  },
  {
    title: 'Đại sứ từ vựng 👑',
    description: 'Hoàn thành xuất sắc các bài học',
    type: MISSION_TYPES.WEEKLY,
    action: MISSION_ACTIONS.COMPLETE_LESSON,
    requirement: 15,
    reward: { xp: 600, stars: 180 },
    iconUrl: getIconUrl('Đại sứ vựng.png', 'https://res.cloudinary.com/demo/image/upload/v1625070000/missions/weekly_complete.png'),
    order: 12,
  },
  {
    title: 'Cao thủ trò chơi 🕹️',
    description: 'Chơi game ôn tập',
    type: MISSION_TYPES.WEEKLY,
    action: MISSION_ACTIONS.PLAY_GAME,
    requirement: 10,
    reward: { xp: 500, stars: 150 },
    iconUrl: getIconUrl('Cao thủ trò chơi.png', 'https://res.cloudinary.com/demo/image/upload/v1625070000/missions/weekly_game.png'),
    order: 13,
  },
  {
    title: 'Cơn mưa quà tặng 🎁',
    description: 'Tích lũy Sao/XP từ mọi hoạt động',
    type: MISSION_TYPES.WEEKLY,
    action: MISSION_ACTIONS.COMPLETE_LESSON,
    requirement: 10,
    reward: { xp: 800, stars: 250 },
    iconUrl: getIconUrl('Cơn mưa quà tặng.png', 'https://res.cloudinary.com/demo/image/upload/v1625070000/missions/weekly_complete.png'),
    order: 14,
  },
  {
    title: 'Bàn tay khéo léo ✍️',
    description: 'Viết chính xác chữ cái/từ vựng',
    type: MISSION_TYPES.WEEKLY,
    action: MISSION_ACTIONS.WRITE_LESSON,
    requirement: 20,
    reward: { xp: 600, stars: 180 },
    iconUrl: getIconUrl('Bàn tay khéo léo.png', 'https://res.cloudinary.com/demo/image/upload/v1625070000/missions/weekly_write.png'),
    order: 15,
  },
];

const seedMissions = async () => {
  try {
    console.log('⏳ Seeding Missions into Database...');

    // Clear existing missions
    const deleteResult = await Mission.deleteMany({});
    console.log(`🧹 Cleared ${deleteResult.deletedCount} old missions.`);

    // Insert new missions
    const insertedMissions = await Mission.insertMany(missions);
    console.log(`🎉 Successfully seeded ${insertedMissions.length} new missions!`);

    return insertedMissions;
  } catch (error) {
    console.error('❌ Error seeding missions:', error.message);
    throw error;
  }
};

// If run directly
if (require.main === module) {
  mongoose.connect(process.env.MONGO_URI)
    .then(() => {
      console.log('🔌 Connected to MongoDB for seeding missions.');
      return seedMissions();
    })
    .then(() => {
      console.log('🔌 Closing connection...');
      return mongoose.connection.close();
    })
    .then(() => {
      console.log('👋 Seeder finished successfully.');
      process.exit(0);
    })
    .catch((err) => {
      console.error('❌ Fatal error in seeder:', err);
      process.exit(1);
    });
}

module.exports = seedMissions;
